version: "3.8"

services:
  auth:
    build:
      context: .
      dockerfile: packages/auth/Dockerfile
      target: ${BUILD_TARGET:-dev} # Default to "dev" if not specified
    container_name: auth
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/app # Mount source code for development (optional for hot reloading)
    depends_on:
      - mongo # Ensure mongo service starts before nginx
    command: ["yarn", "run", "start:dev"] # Use nodemon in development
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27018:27017"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs # Mount certs only for development
    depends_on:
      - auth # Ensure auth service starts before nginx
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: # Declare the named volume here
