version: "3.8"

services:
  auth:
    build:
      context: .
      dockerfile: packages/auth/Dockerfile
      target: ${BUILD_TARGET:-test} 
    container_name: auth_test
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=${NODE_ENV:-test}
    depends_on:
      - mongo # Ensure mongo service starts before nginx
    command: ["yarn", "run", "start:test"]
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27019:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: # Declare the named volume here
